apiVersion: v1
kind: Service
metadata:
  name: topology-service
  labels:
    app: topology
spec:
  selector:
    app: topology
  ports:
    - name: http
      port: 7000
      targetPort: 7000
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
  type: LoadBalancer
